module Call_Exc
   use import int.Int
   use import ref.Ref

  exception Test

  val maybe_increase (x : ref int) : unit
    requires { true }
    writes {x}
    raises {Test -> !x = old !x}
    ensures { !x = old !x + 1}

(* Valid *)

  let test1 (x : ref int)
    requires { true }
    ensures { !x = old !x + 1}
    raises { Test -> !x = old !x }
    =
    maybe_increase x

(* Unknown *)
  let test2 (x : ref int)
    requires { true }
    ensures { !x = old !x + 1}
    raises { Test -> !x = old !x + 1 }
    =
    maybe_increase x

end
